const sqlite3 = require('sqlite3').verbose();
const path = require('path');

const dbPath = path.resolve(__dirname, '../../../../database.sqlite');

async function handleUsersMenu(bot, msg) {
    const chatId = msg.chat.id;
        
            const db = new sqlite3.Database(dbPath);

                db.run(`CREATE TABLE IF NOT EXISTS users (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                                telegram_id TEXT UNIQUE,
                                        username TEXT,
                                                first_name TEXT,
                                                        last_name TEXT,
                                                                balance REAL DEFAULT 0,
                                                                        status TEXT DEFAULT 'ACTIVE',
                                                                                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
                                                                                    )`, () => {
                                                                                            
                                                                                                    db.get(`SELECT COUNT(*) as total FROM users`, async (err, row) => {
                                                                                                                db.close();

                                                                                                                            if (err) {
                                                                                                                                            console.error("Error fetching user stats:", err.message);
                                                                                                                                                            return bot.sendMessage(chatId, "❌ Failed to fetch user statistics.");
                                                                                                                                                                        }

                                                                                                                                                                                    const totalUsers = row ? row.total : 0;

                                                                                                                                                                                                const message = `👥 *Users Management*\n\n` +
                                                                                                                                                                                                                            `📊 *Total Registered Users:* ${totalUsers}\n\n` +
                                                                                                                                                                                                                                                        `Choose an action below:`;

                                                                                                                                                                                                                                                                    await bot.sendMessage(chatId, message, {
                                                                                                                                                                                                                                                                                    parse_mode: 'Markdown',
                                                                                                                                                                                                                                                                                                    reply_markup: {
                                                                                                                                                                                                                                                                                                                        inline_keyboard: [
                                                                                                                                                                                                                                                                                                                                                [{ text: '🚫 Ban / Unban User', callback_data: 'admin_ban_user' }],
                                                                                                                                                                                                                                                                                                                                                                        [{ text: '📢 Send Broadcast', callback_data: 'admin_broadcast' }]
                                                                                                                                                                                                                                                                                                                                                                                            ]
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                    async function handleBanUserPrompt(bot, msg) {
                                                                                                                                                                                                                                                                                                                                                                                                                                        const chatId = msg.chat.id;
                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                const sentMsg = await bot.sendMessage(chatId, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                        "🚫 *Ban / Unban User*\n\n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Please reply with the **Telegram ID** of the user you want to toggle status for:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { parse_mode: 'Markdown' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bot.once('message', async (responseMsg) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (responseMsg.chat.id !== chatId) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const targetId = responseMsg.text.trim();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const db = new sqlite3.Database(dbPath);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                db.get(`SELECT telegram_id, status FROM users WHERE telegram_id = ?`, [targetId], (err, user) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (err || !user) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            db.close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return bot.sendMessage(chatId, `❌ User with ID ${targetId} not found in database.`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const newStatus = user.status === 'BANNED' ? 'ACTIVE' : 'BANNED';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                db.run(`UPDATE users SET status = ? WHERE telegram_id = ?`, [newStatus, targetId], (updateErr) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                db.close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (updateErr) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return bot.sendMessage(chatId, `❌ Failed to update user status.`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    bot.sendMessage(chatId, `✅ Success! User ${targetId} status is now: *${newStatus}*`, { parse_mode: 'Markdown' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async function handleBroadcastPrompt(bot, msg) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const chatId = msg.chat.id;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await bot.sendMessage(chatId, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "📢 *Send Broadcast*\n\n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Please type the message you want to broadcast to all registered users:",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { parse_mode: 'Markdown' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        bot.once('message', async (responseMsg) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (responseMsg.chat.id !== chatId) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const broadcastText = responseMsg.text;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const db = new sqlite3.Database(dbPath);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        db.all(`SELECT telegram_id FROM users`, async (err, users) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    db.close();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (err || !users || users.length === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return bot.sendMessage(chatId, "❌ No users found to broadcast to.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let successCount = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let failCount = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await bot.sendMessage(chatId, `🚀 Broadcasting to ${users.length} users... Please wait.`);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (const user of users) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await bot.sendMessage(user.telegram_id, broadcastText, { parse_mode: 'Markdown' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    successCount++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        failCount++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await bot.sendMessage(chatId, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `📢 *Broadcast Completed!*\n\n` +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `✅ Successfully sent: ${successCount}\n` +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `❌ Failed: ${failCount}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { parse_mode: 'Markdown' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        module.exports = { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            handleUsersMenu, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                handleBanUserPrompt, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    handleBroadcastPrompt 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    